# Generated by Django 5.0.3 on 2024-03-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("PersonID", models.CharField(max_length=50)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("TFN", models.CharField(max_length=50)),
                ("DOB", models.DateField(max_length=15)),
                ("address", models.CharField(max_length=100)),
                ("SelectEmpyeeToCheckSS", models.CharField(max_length=50)),
                ("declarationAcceptance", models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name="Record",
        ),
    ]
